---
title: "bkt power model fit to Southern Apps data"
author: "yk"
date: "January 29, 2016"
output: html_document
---

# 01/29/2016
# Power analysis for detecting a temporal trend in regional brook trout abundance
# Fit a model to southern Apps data compiled by THan Hitt
==================================================================================

## working directory & libraries
```{r working directory & libraries, warning=FALSE, message=FALSE}
setwd("G:/Clemson/Research/Projects/bkt_working_group/Sampling-Design/southern_Apps")
getwd()
library(reshape2); library(rjags); library(plyr); library(ggplot2)
library(knitr); library(arm); library(boot)
load.module("glm")
```

## Read in data from Than's data
```{r Read in data}
# Trout count data
load("G:/Clemson/Research/Projects/bkt_working_group/southern Apps Nmix/2015-11-03 Than/BKTSouth_Nmix/Data_FishCountAr.RData")
# Imports pass-specific count data for each site and year

# Detection covriates data
load("G:/Clemson/Research/Projects/bkt_working_group/southern Apps Nmix/2015-11-03 Than/BKTSouth_Nmix/Data_DetectionCovsStd.RData")
# Imports sampling day-of-year and precip in prior 7 days from DAYMET data (standardized)
```

## prep for JAGS
```{r prep for JAGS}
# data structure
nSites = dim(YOYFish)[1]
nYears = dim(YOYFish)[2]

# bundle data - testing YOY abundance
dat <- list(nSites=nSites, nYears=nYears, y=YOYFish,
            prcp7day=prcp7day.std, sampday=sampday.std)

# set initial values
init <- function() list(mu=runif(1,0,10), 
                        N=array(1000, dim=c(nSites, nYears)),
                        p.mean=runif(1,0,1),
                        p.b=rnorm(2))

# parameters to monitor
pars <- c("mu","trend","sd.slope","sd.year","sigma","sd.wn","wn",
          "p.mean","p.b","p.sigma")
```

## running JAGS
```{r running JAGS}
set.seed(123)
# burn-in
burnin <- jags.model(paste("bkt trend power model.r", sep=""),
                           dat, init, n.chains=3, n.adapt=20000)

# mcmc sample
out <- coda.samples(burnin, pars, n.iter=10000, thin=10)
summary(out)
plot(out)

# gelman r value
library(coda)
gelman.diag(out)
```
